CsTranslator.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CsTranslator.Web.Models;
using Microsoft.Extensions.Options;
using CsTranslator.Application;

namespace CsTranslator.Web.Controllers
{
	public class HomeController : Controller
	{
		private readonly IOptions<AppSettings> _appSettings;

		public HomeController(IOptions<AppSettings>appSettings)
		{
			_appSettings = appSettings;
		}

		public IActionResult Index()
		{
			var vm = new TranslateViewModel
			{
				SourceLanguage = _appSettings.Value.DefaultLanguageInput
			};
			return View(vm);
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

CsTranslator.Web/Controllers/TranslationsController.cs
using CsTranslator.Application.Queries;
using CsTranslator.Web.Dto;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace CsTranslator.Web.Controllers
{
	[Route("api/[controller]")]
	[ApiController]
	public class TranslationsController : ControllerBase
	{
		private readonly IMediator _mediator;

		public TranslationsController(IMediator mediator)
		{
			_mediator = mediator;
		}

		[HttpGet]
		public async Task<ActionResult<TranslationResultDto>> Translate([FromQuery][Required]string translationQuery)
		{
			try
			{
				var result = await _mediator.Send(new TranslateQuery(translationQuery, null, null));
				var dto = new TranslationResultDto(result.TranslatedText);
				return Ok(dto);
			}
			catch (Exception exc)
			{
				return BadRequest(new TranslationResultDto { ErrorMessage = exc.Message });
			}
		}
	}
}

CsTranslator.Web/Views/Home/Index.cshtml
@model TranslateViewModel

<div class="text-center">
    <h1 class="display-5">Enter text to translate</h1>
    <form method="get"
          data-ajax="true"
          data-ajax-method="get"
          data-ajax-success="submitSuccess"
          data-ajax-failure="submitFailure"
          data-ajax-begin="submitBegin"
          data-ajax-complete="submitComplete"
          data-ajax-url="@Url.Action("Translate", "Translations")">
        <div class="form-group">
            <input autofocus class="form-control" asp-for="TranslationQuery" aria-describedby="queryHelp">
            <span asp-validation-for="TranslationQuery" class="text-danger"></span>
            <small id="queryHelp" class="form-text text-muted">
                @if (string.IsNullOrEmpty(Model.SourceLanguage))
                {
                    <span>Input language will automatically be detected</span>
                }
                else
                {
                    <span>Expected input language: <strong>@Model.SourceLanguage</strong></span>
                }
            </small>
        </div>
        <button id="btnSubmit" class="btn btn-primary" type="submit">
            <span id="btnLoading" class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>Translate
        </button>
    </form>
    <h1 class="display-5 translated-text-result">Translated text</h1>
    <h4 id="translated" />
</div>
@section scripts{
    <partial name="_ValidationScriptsPartial" />
    <script>
        function submitSuccess(data) {
            $('#translated').html(data.translatedText);
        }
        function submitFailure(error) {
            console.error('submitFailure', error);
        }
        function submitBegin() {
            $('#btnSubmit').prop('disabled', true);
            $('#btnLoading').removeClass('d-none');
        }
        function submitComplete() {
            $('#btnSubmit').prop('disabled', false);
            $('#btnLoading').addClass('d-none');
        }
    </script>
}